### ISSUE TITLE
Use inlinecss twig tag with a variable

### ISSUE THREAD

**Issue by redayoub** [gushphp/ToInlineStyleEmailBundle#26]
Hi,

Is there a way to use the inlinecss twig tag with a variable, like this:

{% inlinecss styleSheet %}

Thanks

**Comment by redayoub** [comment]
up

**Comment by redayoub** [comment]
up

**Comment by kalypso63** [comment]
+1

**Comment by cordoval** [comment]
done in https://github.com/robertotru/ToInlineStyleEmailBundle/pull/30

**Comment by cordoval** [comment]
https://github.com/robertotru/ToInlineStyleEmailBundle/pull/36/files

**Comment by cordoval** [comment]
#36
