### ISSUE TITLE
Documentation - include conversion

### ISSUE THREAD

**Issue by SecondeJK** [gushphp/ToInlineStyleEmailBundle#28]
Hi guys,

Could you please include generateStyledHTML() in the ReadMe file - I know it seems like common sense, but you've documented the rest of how the Bundle works so it would surely make sense to document the actual parsing?

**Comment by cordoval** [comment]
bump @SecondeJK send a PR

**Comment by cordoval** [comment]
bump @SecondeJK

**Comment by cordoval** [comment]
addressed already on master
