### ISSUE TITLE
Compatibility with tijsverkoyen/css-to-inline-styles v2.2.0

### ISSUE THREAD

**Issue by kalypso63** [gushphp/ToInlineStyleEmailBundle#35]
Your last version are not compatible with tijsverkoyen/css-to-inline-styles v2.2.0. 
Breaking changes with some methods presents on ToInlineStyleEmailConverter class.

**Comment by cordoval** [comment]
working on this @kalypso63 

can you paste some errors too, would help

**Comment by cordoval** [comment]
@kalypso63 i ran into the issues myself today, should be able to fix it now, sorry for the delay

**Comment by aeyoll** [comment]
Hello @cordoval,
PR #39 is fixing this issue, is a merge planned any time soon? Thanks a lot :+1:

**Comment by cordoval** [comment]
yes tomorrow 👍 thanks for corroborating. I told him to send the PR he he

**Comment by cordoval** [comment]
@aeyoll one more day because i am still sick 👍 ship is good now !
